openapi: 3.0.0
info:
  version: 1.0.1
  title: Connect API
  description: API specification for the Connect API
paths:
  "/i/testsend/push/pair/{platform}":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: PairDevice
      summary: Pair Device
      tags:
        - ios
        - android
        - Test Send
      parameters:
        - $ref: "#/components/parameters/x-outbound-key"
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/pair-device"
      responses:
        "200":
          description: ""
  "/i/{platform}/opened":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: Opened
      summary: Opened
      tags:
        - ios
        - android
        - Metrics
      parameters:
        - $ref: "#/components/parameters/x-outbound-key"
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
      requestBody:
        $ref: "#/components/requestBodies/push-basic-metric"
      responses:
        "200":
          description: ""
  "/i/{platform}/received":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: Received
      summary: Received
      tags:
        - ios
        - android
        - Metrics
      parameters:
        - $ref: "#/components/parameters/x-outbound-key"
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
      requestBody:
        $ref: "#/components/requestBodies/push-basic-metric"
      responses:
        "200":
          description: ""
  "/i/{platform}/uninstall_tracker":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: UninstallTracker
      summary: Uninstall Tracker
      tags:
        - ios
        - android
        - Metrics
      parameters:
        - $ref: "#/components/parameters/x-outbound-key"
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/uninstall-tracker"
      responses:
        "200":
          description: ""
  "/i/config/sdk/{platform}/{version}":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: Config
      summary: Config
      tags:
        - ios
        - android
        - Config
      parameters:
        - $ref: "#/components/parameters/x-outbound-key"
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/config"
              examples:
                response:
                  value:
                    enabled: false
                    sdk: {}
                    account: {}
  "/v2/{platform}/register":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: Register
      summary: Register
      tags:
        - ios
        - android
        - Push
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        $ref: "#/components/requestBodies/push-registration"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
  "/v2/{platform}/disable":
    parameters:
      - name: platform
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: Unregister
      summary: Unregister
      tags:
        - ios
        - android
        - Push
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        $ref: "#/components/requestBodies/push-registration"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
  /v2/track:
    post:
      operationId: Track
      summary: Track
      tags:
        - ios
        - android
        - Event
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/event"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
  /v2/track/batch:
    post:
      operationId: TrackBatch
      summary: Track Batch
      tags:
        - ios
        - android
        - Event
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/event"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
  /v2/identify:
    post:
      operationId: Identify
      summary: Identify
      tags:
        - ios
        - android
        - Identify
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
  /v2/identify/batch:
    post:
      operationId: IdentifyBatch
      summary: Identify Batch
      tags:
        - ios
        - android
        - Identify
      parameters:
        - $ref: "#/components/parameters/x-outbound-client"
        - $ref: "#/components/parameters/x-outbound-guid"
        - $ref: "#/components/parameters/x-outbound-key"
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/user"
      responses:
        "200":
          description: ""
      security:
        - X-Outbound-Key: []
servers:
  - url: https://api.outbound.io
components:
  parameters:
    x-outbound-guid:
      name: "X-Outbound-GUID"
      in: header
      required: true
      schema:
        type: string
    x-outbound-client:
      name: "X-Outbound-Client"
      in: header
      required: true
      schema:
        type: string
    x-outbound-key:
      name: "X-Outbound-Key"
      in: header
      required: true
      schema:
        type: string
  requestBodies:
    push-basic-metric:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/push-basic-metric"
    push-registration:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/push-registration"
  schemas:
    dictionary-less-than-string-any-greater-than:
      title: "Dictionary<String, Any>"
      type: object
    model-timestamp:
      title: "ModelTimestamp"
      type: object
    push-registration:
      title: "Push Registration"
      type: object
      properties:
        timestamp:
          $ref: "#/components/schemas/model-timestamp"
        user_id:
          type: string
        token:
          type: string
      required:
        - user_id
      example:
        timestamp: ipsum Duis
        user_id: commodo nulla aliquip
        token: mollit sed
    event:
      title: "Event"
      type: object
      properties:
        user_id:
          type: string
        timestamp:
          $ref: "#/components/schemas/model-timestamp"
        properties:
          $ref: "#/components/schemas/dictionary-less-than-string-any-greater-than"
        event:
          type: string
      required:
        - user_id
        - event
      example:
        user_id: pro
        timestamp: 38857730
        property: {}
        event: commodo amet pariatur officia laborum
    config:
      title: "Config"
      type: object
      properties:
        enabled:
          type: boolean
        account:
          $ref: "#/components/schemas/account-config"
      example:
        enabled: false
        sdk: {}
        account: {}
    user:
      title: "User"
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        attributes:
          $ref: "#/components/schemas/dictionary-less-than-string-any-greater-than"
        user_id:
          type: string
        previous_id:
          type: string
        phone_number:
          type: string
        group_id:
          type: string
        group_attributes:
          $ref: "#/components/schemas/dictionary-less-than-string-any-greater-than"
        timezone:
          type: string
        gcm:
          type: array
          items:
            type: string
        apns:
          type: array
          items:
            type: string
      required:
        - user_id
      example:
        first_name: in dolor incididunt mollit dolore
        last_name: in ea
        email: ullamco in exercitation
        attributes: {}
        user_id: esse ea
        previous_id: ut Excepteur laboris
        phone_number: adipisicing ut ad
        group_id: aliqua fugiat sunt
        group_attributes: {}
        timezone: dolor culpa in Lorem velit
        gcm:
          - sunt tempor ut nulla reprehenderit
          - ad
          - laboris nostrud dolore eiusmod
    account-config:
      title: "Account Config"
      type: object
      properties:
        prompt:
          type: boolean
        prompt_event:
          type: string
        pre_prompt:
          $ref: "#/components/schemas/pre-prompt"
    pre-prompt:
      title: "Prompt"
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        no_button:
          type: string
        yes_button:
          type: string
    push-basic-metric:
      title: "Push Basic Metric"
      type: object
      properties:
        _oid:
          type: string
    uninstall-tracker:
      title: "Uninstall Tracker"
      type: object
      properties:
        i:
          type: string
        revoked:
          type: boolean
    pair-device:
      title: "Pair Device"
      type: object
      properties:
        code:
          type: number
        deviceToken:
          type: string
        deviceName:
          type: string